name: piotrlange
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  dart_emoji: ^0.2.0+2
  staurolite:
    git: 
      url: https://github.com/piotrzpl/staurolite
  yaml: ^3.1.1
